/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CeoService } from "../ceo.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CeoCreateInput } from "./CeoCreateInput";
import { Ceo } from "./Ceo";
import { CeoFindManyArgs } from "./CeoFindManyArgs";
import { CeoWhereUniqueInput } from "./CeoWhereUniqueInput";
import { CeoUpdateInput } from "./CeoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CeoControllerBase {
  constructor(
    protected readonly service: CeoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Ceo })
  @nestAccessControl.UseRoles({
    resource: "Ceo",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: CeoCreateInput,
  })
  async createCeo(@common.Body() data: CeoCreateInput): Promise<Ceo> {
    return await this.service.createCeo({
      data: {
        ...data,

        company: {
          connect: data.company,
        },

        person: {
          connect: data.person,
        },
      },
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        fromDate: true,
        id: true,

        person: {
          select: {
            id: true,
          },
        },

        untilDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Ceo] })
  @ApiNestedQuery(CeoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Ceo",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ceos(@common.Req() request: Request): Promise<Ceo[]> {
    const args = plainToClass(CeoFindManyArgs, request.query);
    return this.service.ceos({
      ...args,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        fromDate: true,
        id: true,

        person: {
          select: {
            id: true,
          },
        },

        untilDate: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Ceo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ceo",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ceo(@common.Param() params: CeoWhereUniqueInput): Promise<Ceo | null> {
    const result = await this.service.ceo({
      where: params,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        fromDate: true,
        id: true,

        person: {
          select: {
            id: true,
          },
        },

        untilDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Ceo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ceo",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: CeoUpdateInput,
  })
  async updateCeo(
    @common.Param() params: CeoWhereUniqueInput,
    @common.Body() data: CeoUpdateInput
  ): Promise<Ceo | null> {
    try {
      return await this.service.updateCeo({
        where: params,
        data: {
          ...data,

          company: {
            connect: data.company,
          },

          person: {
            connect: data.person,
          },
        },
        select: {
          company: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          fromDate: true,
          id: true,

          person: {
            select: {
              id: true,
            },
          },

          untilDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Ceo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ceo",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCeo(
    @common.Param() params: CeoWhereUniqueInput
  ): Promise<Ceo | null> {
    try {
      return await this.service.deleteCeo({
        where: params,
        select: {
          company: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          fromDate: true,
          id: true,

          person: {
            select: {
              id: true,
            },
          },

          untilDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
